/*
 * generated by Xtext 2.39.0
 */
package org.eclipse.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainmodelScopeProvider extends DelegatingScopeProvider {
}
