/*
 * generated by Xtext 2.39.0
 */
package org.eclipse.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.example.DomainmodelRuntimeModule;
import org.eclipse.xtext.example.DomainmodelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DomainmodelIdeSetup extends DomainmodelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomainmodelRuntimeModule(), new DomainmodelIdeModule()));
	}
	
}
