/*
 * generated by Xtext 2.39.0
 */
package org.eclipse.xtext.example.ide;


/**
 * Use this class to register ide components.
 */
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
