/*
 * generated by Xtext 2.39.0
 */
package org.eclipse.xtext.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DomainmodelStandaloneSetup extends DomainmodelStandaloneSetupGenerated {

	public static void doSetup() {
		new DomainmodelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
