/*
 * generated by Xtext 2.39.0
 */
package org.eclipse.xtext.example;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainmodelRuntimeModule extends AbstractDomainmodelRuntimeModule {
}
