/*
 * generated by Xtext 2.39.0
 */
package org.eclipse.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DomainmodelUiModule extends AbstractDomainmodelUiModule {

	public DomainmodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
